Repository bnhoang2k/friends, pull requests merged in 2024-10, with the labels that each got.

#21 Improved login flow to create tvm clients when needed and duplicate c…
  friends/Misc/Social/TypesenseManager.swift
  friends/Models/TypesenseVM.swift
  friends/Views/Authentication/GetInformationView.swift
  friends/Views/Root/MainView.swift
  friends/Views/Root/RootView.swift
  friends/Views/User Settings/UserProfileView.swift
Labels: enhancement

#23 docs(.cz.toml): added a basic commitizen configuration file
  .cz.toml
  .pre-commit-config.yaml
Labels: documentation

#26 fix(devenv.nix): added pre-commit as a dependency
  devenv.nix
Labels: bug
